name: Term-ANSIScreen
version: 1.41
abstract: Terminal control using ANSI escape sequences
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
